title: InfoSec WirteUps
slogan: all you need to kNow
#logo: "assets/uploads/profile.jpg"

# baseurl: ""
url: "https://ZishanAdThandar.github.io"

collections:
  notes:
    output: true
   

defaults:
  - scope:
      path: /
    values:
      layout: post
      author: Zishan Ahamed Thandar  
  

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  # - jekyll-paginate
  - kramdown

markdown: kramdown
# paginate: 5
# paginate_path: "/page:num"
